function M = function_M_Rot
%function_M_Rot
%    M = function_M_Rot

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    04-Dec-2025 20:54:53

M = reshape([4.4176254976e-3,1.31754312e-3,1.31754312e-3,1.31754312e-3],[2,2]);
end
