function V = function_V_Rot(theta1_p,theta2_p)
%function_V_Rot
%    V = function_V_Rot(THETA1_P,THETA2_P)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    06-Mar-2026 18:08:31

V = [theta1_p.*6.241020287737004e-4;theta2_p.*7.89068265583448e-3];
end
