function G = function_G_Rot(theta1)
%function_G_Rot
%    G = function_G_Rot(THETA1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    06-Mar-2026 18:08:31

G = [sin(theta1).*(-3.462480702e-1);0.0];
end
