function P = function_P_Rot
%function_P_Rot
%    P = function_P_Rot

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    06-Mar-2026 18:08:31

P = [0.0;1.96e+2./6.25e+2];
end
